feat: add ZkEvmReceiver
sparkdotfi/xchain-helpers pull request #11
Opened 2023-10-29 11:55 UTC by 0xdapper

2023-11-01 12:12 UTC, hexonaut requested changes
Requesting a number of changes. Please note to other reviewers you can use https://github.com/0xPolygonHermez/code-examples/blob/main/pingPongExample/contracts/PingReceiver.sol#L65 for comparison.

2023-11-01 12:12 UTC, hexonaut commented on src/ZkEvmReceiver.sol
> +    modifier onlySelf() {
Let's change this to `onlyCrossChainMessage` to match the other receivers. The goal is uniformity of usage.

2023-11-01 12:12 UTC, hexonaut commented on src/ZkEvmReceiver.sol
> +        require(msg.sender == bridge, "Receiver/invalid-caller");
Let's change this to `Receiver/invalid-sender`.

2023-11-01 12:12 UTC, hexonaut commented on src/ZkEvmReceiver.sol
> +        require(originAddress == l1Authority, "Receiver/invalid-l1Authority");
We should also check the origin network which should be supplied via the constructor. Additionally the alignment should match the style of other receivers like this: https://github.com/marsfoundation/xchain-helpers/blob/master/src/GnosisReceiver.sol#L34

2023-11-01 12:12 UTC, hexonaut commented on test/ZkEVMIntegration.t.sol
> +contract ZkevmMessageOrdering is MessageOrdering, ZkEvmReceiver {
Let's match the casing: `ZkEVM`.

2023-11-01 12:12 UTC, hexonaut commented on test/ZkEVMIntegration.t.sol
> +        moZkevm.push(999);
Two additional failure tests should be added for the cases where the `msg.sender` is not the bridge and the origin network is not correct when that is added.

2023-11-02 03:56 UTC, 0xdapper commented on src/ZkEvmReceiver.sol
> +    address constant bridge = 0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe;
not sure, I've asked. I assumed because it is same on L1 bridge and L2 bridge it will be same on other L2 deployments as well.

2023-11-04 11:13 UTC, 0xdapper commented on src/ZkEvmReceiver.sol
> +    address constant bridge = 0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe;
Team has confirmed that it will always be the same address

2023-11-06 16:18 UTC, hexonaut requested changes
Looking much better. One more change, and this looks good to me.

2023-11-06 16:18 UTC, hexonaut commented on src/ZkEVMReceiver.sol
> +    function onMessageReceived(address originAddress, uint32 originNetwork, bytes calldata data) external payable {
Let's make this `virtual` so it can be overridden in case the implementing contract needs to get the arguments.

2023-11-10 13:21 UTC, hexonaut approved these changes
Good to merge after Polygon has internal reviewer/auditor.

2023-11-17 10:43 UTC, barrutko approved these changes

2025-04-12 18:49 UTC, closed without merging